spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/moviebooking
spring.datasource.username=root
spring.datasource.password=Nishant123@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
app.jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
app.jwt.expiration-ms=28800000
app.jwt.refresh-expiration-ms=604800000

# Cloudinary Configuration
cloudinary.cloud-name=dku0z3smq
cloudinary.api-key=665582796213282
cloudinary.api-secret=yqrp4wxORXX3pRK8BwIinLV2v94

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=s.jayanthkumar12@gmail.com
spring.mail.password=hyoaqyinbqmaoclh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Super Admin Config
app.superadmin.email=jayanthkumarsamatham@gmail.com

# OMDb API (movie data provider)
omdb.api-key=15447beb
omdb.base-url=http://www.omdbapi.com/